[package]
name = "llm"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
util = { path = "../util" }
serde.workspace = true
serde_json.workspace = true
reqwest.workspace = true
parking_lot.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
axum.workspace = true

[dev-dependencies]
test_support = { path = "../test_support" }

[lints]
workspace = true
