[package]
name = "graph"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base = { path = "../base" }
math = { path = "../math" }
store = { path = "../store" }
util = { path = "../util" }
serde.workspace = true
bincode.workspace = true
serde_json.workspace = true
tracing.workspace = true
parking_lot.workspace = true
rand.workspace = true
rayon.workspace = true
memmap2 = "0.9"
thiserror.workspace = true

[dev-dependencies]
tempfile = "3"
test_support = { path = "../test_support" }

[lints]
workspace = true
